name: Release

on:
  release:
    types: [published]

jobs:
  release-package:
    name: Release Package
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v6

    - name: Prepare artefacts
      run: |
        make dist
    
    - name: Create ZIP archive
      run: |
        zip -r dist.zip dist

    - name: Upload release assets
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: dist.zip
